In [7]:
import jax
import jax.numpy as jnp
import numpy as np

In [11]:
layer_sizes = [1, 3, 2, 2, 1]

In [12]:
params = {}
for i, (n_in, n_out) in enumerate(zip(layer_sizes[:-1], layer_sizes[1:])):
    params[f"layer_{i}"] = {"weights": np.random.randn(n_in, n_out) , "biases": np.ones(n_out, )}

In [13]:
params

{'layer_0': {'weights': array([[ 0.32127894, -0.90215931, -0.13716245]]),
  'biases': array([1., 1., 1.])},
 'layer_1': {'weights': array([[ 0.62946452,  1.04976083],
         [-1.04683001,  0.10236843],
         [ 0.92451111,  0.46405542]]),
  'biases': array([1., 1.])},
 'layer_2': {'weights': array([[ 0.49116094, -0.61675675],
         [-0.09043199, -1.15349577]]),
  'biases': array([1., 1.])},
 'layer_3': {'weights': array([[ 1.00058301],
         [-1.13532627]]),
  'biases': array([1.])}}

In [14]:
jax.tree_structure(params)

PyTreeDef({'layer_0': {'biases': *, 'weights': *}, 'layer_1': {'biases': *, 'weights': *}, 'layer_2': {'biases': *, 'weights': *}, 'layer_3': {'biases': *, 'weights': *}})

In [16]:
jax.tree_map(lambda x: x.shape, params)

{'layer_0': {'biases': (3,), 'weights': (1, 3)},
 'layer_1': {'biases': (2,), 'weights': (3, 2)},
 'layer_2': {'biases': (2,), 'weights': (2, 2)},
 'layer_3': {'biases': (1,), 'weights': (2, 1)}}

In [17]:
jax.tree_leaves(params)

[array([1., 1., 1.]),
 array([[ 0.32127894, -0.90215931, -0.13716245]]),
 array([1., 1.]),
 array([[ 0.62946452,  1.04976083],
        [-1.04683001,  0.10236843],
        [ 0.92451111,  0.46405542]]),
 array([1., 1.]),
 array([[ 0.49116094, -0.61675675],
        [-0.09043199, -1.15349577]]),
 array([1.]),
 array([[ 1.00058301],
        [-1.13532627]])]

In [18]:
*hidden, last = params
last

'layer_3'

In [20]:
len(params)

4

In [21]:
activations = [jax.nn.relu, jax.nn.relu, jax.nn.relu, lambda x: x]

In [22]:
def forward(params, activations, x):
    for i, (layer_name, layer_params) in enumerate(params.items()):
        x = activations[i](x @ layer_params['weights'] + layer_params['biases'])
    return x

In [23]:
forward(params, activations, x)

NameError: name 'x' is not defined